vamp:
  environment:
    VAMP_DB_TYPE: "${vamp_db_type}"
    VAMP_DB_PORT: "${vamp_db_port}"
    VAMP_KEY_TYPE: "${vamp_key_type}"
    VAMP_KEY_PORT: "${vamp_key_port}"
    VAMP_KEY_PATH=${VAMP_KEY_PATH: "${vamp_key_path}"
    VAMP_HEAP_OPTS: "-Xmx${vamp_mem}G -Xms${vamp_mem}G"
    VAMP_DRIVER: "${vamp_driver}"
    VAMP_DRIVER_URL: "${vamp_driver_url}"
  external_links:
  - ${vamp_key}:${vamp_key_type}
  - ${vamp_db}:${vamp_db_type}
  tty: true
  image: rawmind/alpine-vamp:0.8.5
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
vamp-ui:
  external_links:
  - vamp:vamp
  tty: true
  image: rawmind/alpine-vamp-ui:0.8.4-7
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
