name: Vamp
description: |
  (Experimental) Vamp core
version: 0.8.5-rancher1
category: clustering
maintainer: "Raul Sanchez <raul.sanchez.liebana@bbva.com>"
minimum_rancher_version: v0.59.0
license: 
